/**
 * Database type placeholder — generated by Supabase CLI.
 * Run: npx supabase gen types typescript --local > src/types/database.ts
 * to replace this file with actual generated types.
 */

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          display_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          university: string | null;
          year_of_study: number | null;
          timezone: string;
          onboarding_completed: boolean;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          university?: string | null;
          year_of_study?: number | null;
          timezone?: string;
          onboarding_completed?: boolean;
          metadata?: Record<string, unknown>;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      squads: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          avatar_url: string | null;
          invite_code: string;
          is_personal: boolean;
          max_members: number;
          created_by: string;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          avatar_url?: string | null;
          invite_code: string;
          is_personal?: boolean;
          max_members?: number;
          created_by: string;
          metadata?: Record<string, unknown>;
        };
        Update: Partial<Database["public"]["Tables"]["squads"]["Insert"]>;
      };
      // Additional tables will be generated by: npx supabase gen types typescript --local
    };
    Views: Record<string, never>;
    Functions: {
      get_user_squad_ids: {
        Args: Record<string, never>;
        Returns: string[];
      };
      has_squad_role: {
        Args: { target_squad_id: string; required_roles: string[] };
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
  };
};
